import { describe, it, expect } from 'vitest'

import fixture from './catalog.data.json'
import { supportsVision, modelContext, type RichModel } from './aicatalog'

/**
 * Integrity of the checked-in openrouter catalog fixture (regenerated by
 * scripts/sync-models.mjs). Guards the shape the catalog surface depends on and the
 * HONESTY invariants: no fabricated blurbs, capability flags derived from the prior's
 * own fields, a browsable count. If the prior changes shape, this fails loudly rather
 * than shipping a silently-degraded catalog.
 */
describe('catalog.data.json — openrouter fixture', () => {
  const models = (fixture as { models: RichModel[] }).models

  it('carries a browsable, versioned corpus', () => {
    expect((fixture as { source: string }).source).toContain('enso-bench')
    expect(models.length).toBeGreaterThan(100)
    expect((fixture as { count: number }).count).toBe(models.length)
  })

  it('every row has a stable id and name — never a blank picker row', () => {
    for (const m of models) {
      expect(typeof m.id).toBe('string')
      expect((m.id ?? '').length).toBeGreaterThan(0)
      expect((m.name ?? '').length).toBeGreaterThan(0)
    }
  })

  it('never fabricates a description (the prior carries none)', () => {
    expect(models.every((m) => m.description === undefined)).toBe(true)
  })

  it('derives the Vision capability from the prior, not a guess', () => {
    // A known vision model reads Vision; a known text-only model does not.
    const jamba = models.find((m) => m.id === 'ai21/jamba-large-1.7')!
    expect(supportsVision(jamba)).toBe(false) // text-only in the prior
    const anyVision = models.find((m) => supportsVision(m))
    expect(anyVision).toBeDefined()
    expect((anyVision!.features ?? []).map((f) => f.toLowerCase())).toContain('vision')
  })

  it('context + price are real numbers or absent (never zero-filled)', () => {
    const jamba = models.find((m) => m.id === 'ai21/jamba-large-1.7')!
    expect(modelContext(jamba)).toBe(256000)
    expect(jamba.pricing?.input).toBe(2)
    // A free model keeps its honest isFree flag rather than a fabricated price.
    const free = models.find((m) => m.isFree === true)
    if (free) expect(free.isFree).toBe(true)
  })
})
