# console2 — Hanzo Cloud Console (Next.js 15 + @hanzo/gui). BSD-3-Clause.
# NEXT_PUBLIC_* are inlined at build time (browser config), so they are build args.
FROM ghcr.io/hanzoai/nodejs:24-alpine AS build
WORKDIR /app
COPY package.json package-lock.json* ./
# npm install (not ci): @hanzo/gui pulls a react-native dep tree whose
# platform/optional packages (e.g. react-native-worklets) resolve differently
# across npm versions, so a lockfile generated by one npm fails `npm ci` under
# another (EUSAGE "Missing: react-native-worklets@... from lock file"). install
# reconciles the tree deterministically for the build platform.
#
# Install + build in ONE stage (no cross-stage `COPY --from=deps node_modules`):
# the prior split intermittently lost `node_modules/.bin/next` in the deps→build
# COPY under Kaniko ("sh: next: not found" at build despite a clean install), a
# symlink-handoff fragility. Keeping install and `next build` on the same
# filesystem removes that seam entirely; the runner stage still copies the final
# node_modules (runtime `next start` worked through that COPY all along).
# The full @hanzo/gui dep tree intermittently completes with ~80 packages missing
# (incl. next) — npm reports success but skips them. Retry-hardened install, then a
# hard assert + explicit repair so a partial tree fails LOUDLY (or self-heals)
# instead of surfacing later as a confusing "next not found".
RUN npm install --no-audit --no-fund --fetch-retries=5 --fetch-retry-mintimeout=20000 --fetch-timeout=120000 \
 && { [ -f node_modules/next/dist/bin/next ] || npm install --no-audit --no-fund next@15.5.19 ; } \
 && test -f node_modules/next/dist/bin/next
COPY . .
# public/ may be empty (git doesn't track empty dirs) — ensure it exists for the runner COPY.
RUN mkdir -p public
# ONE brand-agnostic image: brand (IAM org/issuer/app + wordmark) is resolved at
# RUNTIME from the request hostname (src/config/index.ts), and /v1 is same-origin
# per host. Baking NEXT_PUBLIC_* here would inline a single brand and break that —
# so nothing brand-specific is baked.
# Next 15 + @hanzo/gui (large RN dep tree) overflows Node's default heap on the
# build node → OOMKill (exit 137). Cap the heap generously, as every other Hanzo
# Next build does (chat uses 4096).
ENV NEXT_TELEMETRY_DISABLED=1 NODE_OPTIONS=--max-old-space-size=6144
# Invoke next via its real entry, not the .bin/next symlink: the /gui RN dep
# tree intermittently drops node_modules/.bin/next under the build npm even though
# the next package installs fine ("sh: next: not found"). Running the dist bin
# directly is symlink-independent and deterministic.
RUN node node_modules/next/dist/bin/next build

FROM ghcr.io/hanzoai/nodejs:24-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production NEXT_TELEMETRY_DISABLED=1 PORT=4000
RUN addgroup -S app && adduser -S app -G app
COPY --from=build /app/.next ./.next
COPY --from=build /app/public ./public
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/package.json ./package.json
COPY --from=build /app/next.config.mjs ./next.config.mjs
USER app
EXPOSE 4000
CMD ["node", "node_modules/next/dist/bin/next", "start", "-p", "4000"]
