# console2 — Hanzo Cloud Console (Next.js 15 + @hanzo/gui). BSD-3-Clause.
# NEXT_PUBLIC_* are inlined at build time (browser config), so they are build args.
FROM public.ecr.aws/docker/library/node:22-alpine AS deps
WORKDIR /app
COPY package.json package-lock.json* ./
# npm install (not ci): @hanzo/gui pulls a react-native dep tree whose
# platform/optional packages (e.g. react-native-worklets) resolve differently
# across npm versions, so a lockfile generated by one npm fails `npm ci` under
# another (EUSAGE "Missing: react-native-worklets@... from lock file"). install
# reconciles the tree deterministically for the build platform.
RUN npm install --no-audit --no-fund

FROM public.ecr.aws/docker/library/node:22-alpine AS build
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
# public/ may be empty (git doesn't track empty dirs) — ensure it exists for the runner COPY.
RUN mkdir -p public
# ONE brand-agnostic image: brand (IAM org/issuer/app + wordmark) is resolved at
# RUNTIME from the request hostname (src/config/index.ts), and /v1 is same-origin
# per host. Baking NEXT_PUBLIC_* here would inline a single brand and break that —
# so nothing brand-specific is baked.
# Next 15 + @hanzo/gui (large RN dep tree) overflows Node's default heap on the
# build node → OOMKill (exit 137). Cap the heap generously, as every other Hanzo
# Next build does (chat uses 4096).
ENV NEXT_TELEMETRY_DISABLED=1 NODE_OPTIONS=--max-old-space-size=6144
RUN npm run build

FROM public.ecr.aws/docker/library/node:22-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production NEXT_TELEMETRY_DISABLED=1 PORT=4000
RUN addgroup -S app && adduser -S app -G app
COPY --from=build /app/.next ./.next
COPY --from=build /app/public ./public
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/package.json ./package.json
COPY --from=build /app/next.config.mjs ./next.config.mjs
USER app
EXPOSE 4000
CMD ["npm", "run", "start"]
